### ISSUE TITLE
Songs sometimes repeate even when Repeate is not set

### ISSUE THREAD

**Issue by charlesdaniels** [flaviotordini/musique#18] opened 2019-01-23 15:00 UTC
Tested on Musique 1.5 installed from the vendor supplied deb package on Ubuntu 18.04 (the version of Musique packaged in the Ubuntu repos is broken).

```
cad@eos:~ > uname -a
Linux eos 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
cad@eos:~ > cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
cad@eos:~ > cat /etc/debian_version
buster/sid
cad@eos:~ > dpkg --list | grep -i musique
ii  musique                               1.5                                          amd64        Music player
```

Symptom is that occasionally and seemingly at random, a song from the queue will be played twice in a row when it was only queued once.

**Comment by flaviotordini** [comment] 2019-01-25 10:02
Yes, Musique recently moved away from Phonon, which is the cause of this bug. This is already fixed on Git.

**Closed by flaviotordini** 2019-01-25 10:02 UTC

**Comment by charlesdaniels** [comment] 2019-01-25 16:32
I would test this, but I get a bunch of errors along the lines of `[unknown] "Audio codec not found"`. This does not happen with the `.deb` release. I don't have the bandwidth to debug further right now. Looking forward to a new release!
